(function () {
    "use strict";

    window.IAN_CATALOG = {
        currency: "USD",
        categories: [
            { id: "cabinetry", name: "Cabinetry" },
            { id: "sinks-faucets", name: "Sinks & Faucets" },
            { id: "countertops", name: "Countertops" },
            { id: "appliances", name: "Appliances" },
            { id: "storage-accessories", name: "Storage Accessories" },
            { id: "hardware-components", name: "Hardware & Components" }
        ],
        products: [
            {
                id: "mini-smart-kitchen",
                url: "products/compact-smart-kitchen",
                category: "cabinetry",
                name: "Compact Smart Kitchen with Pull-Out Storage",
                code: "OLCG026",
                badge: "Glass Kitchen",
                image: "img/products/mini-smart-kitchen/1.jpg",
                images: [
                    "img/products/mini-smart-kitchen/1.jpg",
                    "img/products/mini-smart-kitchen/2.jpg",
                    "img/products/mini-smart-kitchen/3.jpg",
                    "img/products/mini-smart-kitchen/4.jpg",
                    "img/products/mini-smart-kitchen/5.jpg",
                    "img/products/mini-smart-kitchen/6.jpg"
                ],
                imageAlt: "Compact modern kitchen with smart pull-out cabinet storage",
                price: 640,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A compact modular kitchen planned for apartments, combining clean modern lines with practical pull-out storage.",
                highlights: ["Space-efficient apartment layout", "Pull-out storage options", "Custom dimensions and finishes"],
                specifications: {
                    "Model": "OLCG026",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Solid wood",
                    "Door finish": "Solid wood",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/glass-kitchen-cabinet/62749414.html"
            },
            {
                id: "aluminium-frame-kitchen",
                url: "products/aluminium-frame-modular-kitchen",
                category: "cabinetry",
                name: "Aluminium-Frame Modular Kitchen",
                code: "OLCG025",
                badge: "Glass Kitchen",
                image: "img/products/aluminium-frame-kitchen/1.jpg",
                images: [
                    "img/products/aluminium-frame-kitchen/1.jpg",
                    "img/products/aluminium-frame-kitchen/2.jpg",
                    "img/products/aluminium-frame-kitchen/3.jpg",
                    "img/products/aluminium-frame-kitchen/4.jpg",
                    "img/products/aluminium-frame-kitchen/5.jpg",
                    "img/products/aluminium-frame-kitchen/6.jpg"
                ],
                imageAlt: "Modern modular kitchen with painted aluminium-frame cabinetry",
                price: 638,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A contemporary modular kitchen pairing painted aluminium-frame detailing with durable wood-based cabinetry.",
                highlights: ["Painted aluminium-frame detailing", "Modular cabinet configuration", "Custom colours and dimensions"],
                specifications: {
                    "Model": "OLCG025",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Solid wood",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/glass-kitchen-cabinet/62749412.html"
            },
            {
                id: "shaker-storage-kitchen",
                url: "products/modern-shaker-storage-kitchen",
                category: "cabinetry",
                name: "Modern Shaker Kitchen with Smart Storage",
                code: "OLCG012",
                badge: "Glass Kitchen",
                image: "img/products/shaker-storage-kitchen/1.jpg",
                images: [
                    "img/products/shaker-storage-kitchen/1.jpg",
                    "img/products/shaker-storage-kitchen/2.jpg",
                    "img/products/shaker-storage-kitchen/3.jpg",
                    "img/products/shaker-storage-kitchen/4.jpg",
                    "img/products/shaker-storage-kitchen/5.jpg",
                    "img/products/shaker-storage-kitchen/6.jpg"
                ],
                imageAlt: "Modern Shaker-style kitchen with glass doors and integrated storage",
                price: 638,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A modern Shaker-inspired kitchen system with glass door elements and configurable internal storage accessories.",
                highlights: ["Shaker-inspired detailing", "Glass door elements", "Flexible internal storage"],
                specifications: {
                    "Model": "OLCG012",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Glass",
                    "Door finish": "Lacquer",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/glass-kitchen-cabinet/62749397.html"
            },
            {
                id: "minimalist-glass-kitchen",
                url: "products/minimalist-glass-front-kitchen",
                category: "cabinetry",
                name: "Minimalist Glass-Front Kitchen",
                code: "OLCG051",
                badge: "Glass Kitchen",
                image: "img/products/minimalist-glass-kitchen/1.jpg",
                images: [
                    "img/products/minimalist-glass-kitchen/1.jpg",
                    "img/products/minimalist-glass-kitchen/2.jpg",
                    "img/products/minimalist-glass-kitchen/3.jpg",
                    "img/products/minimalist-glass-kitchen/4.jpg",
                    "img/products/minimalist-glass-kitchen/5.jpg",
                    "img/products/minimalist-glass-kitchen/6.jpg"
                ],
                imageAlt: "Minimalist kitchen with lacquered cabinetry and glass-front doors",
                price: 638,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A refined kitchen composition combining lacquered particleboard cabinetry with glass-front display storage.",
                highlights: ["Lacquer and glass combination", "Display and concealed storage", "Project-specific planning"],
                specifications: {
                    "Model": "OLCG051",
                    "Application": "Apartment",
                    "Design style": "Rustic / contemporary classic",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard and glass",
                    "Door finish": "Lacquer and glass",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/glass-kitchen-cabinet/62749743.html"
            },
            {
                id: "high-gloss-kitchen",
                url: "products/high-gloss-modern-kitchen",
                category: "cabinetry",
                name: "High-Gloss Modern Kitchen",
                code: "OLCG038-1",
                badge: "Glass Kitchen",
                image: "img/products/high-gloss-kitchen/1.jpg",
                images: [
                    "img/products/high-gloss-kitchen/1.jpg",
                    "img/products/high-gloss-kitchen/2.jpg",
                    "img/products/high-gloss-kitchen/3.jpg",
                    "img/products/high-gloss-kitchen/4.jpg",
                    "img/products/high-gloss-kitchen/5.jpg",
                    "img/products/high-gloss-kitchen/6.jpg"
                ],
                imageAlt: "High-gloss modern modular kitchen cabinet design",
                price: 509,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A clean high-gloss kitchen cabinet system for modern apartments, configurable in layout, colour and accessories.",
                highlights: ["High-gloss contemporary finish", "Custom layout and colour", "Integrated accessory options"],
                specifications: {
                    "Model": "OLCG038-1",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/glass-kitchen-cabinet/62749568.html"
            },
            {
                id: "premium-brown-kitchen",
                url: "products/premium-brown-modular-kitchen",
                category: "cabinetry",
                name: "Premium Brown Modular Kitchen with Island",
                code: "OLCG027-1",
                badge: "Glass Kitchen",
                image: "img/products/premium-brown-kitchen/1.jpg",
                images: [
                    "img/products/premium-brown-kitchen/1.jpg",
                    "img/products/premium-brown-kitchen/2.jpg",
                    "img/products/premium-brown-kitchen/3.jpg",
                    "img/products/premium-brown-kitchen/4.jpg",
                    "img/products/premium-brown-kitchen/5.jpg",
                    "img/products/premium-brown-kitchen/6.jpg"
                ],
                imageAlt: "Premium brown modular kitchen cabinets with island and open display storage",
                imageAlts: [
                    "Premium brown modular kitchen with island in an open-plan interior",
                    "Brown kitchen cabinets with quartz island and dining seating",
                    "Full brown modular kitchen cabinet layout with integrated appliances",
                    "Tall brown kitchen storage cabinet with open display shelving",
                    "Brown tall-unit kitchen cabinets with built-in oven",
                    "Brown wood-effect kitchen cabinets with quartz countertop"
                ],
                price: 509,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A warm brown modular kitchen system with an island, integrated tall units and a balanced mix of concealed and display storage.",
                seoDescription: "Premium brown modular kitchen cabinets with island, quartz countertop and custom storage. Model OLCG027-1, from USD 509 per metre.",
                highlights: ["Coordinated island and tall-unit layout", "Warm wood-effect finish", "Custom dimensions and storage planning"],
                specifications: {
                    "Model": "OLCG027-1",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/glass-kitchen-cabinet/62749506.html"
            },
            {
                id: "smart-shaker-kitchen",
                url: "products/smart-shaker-kitchen-storage",
                category: "cabinetry",
                name: "Smart Shaker Kitchen with Integrated Storage",
                code: "OLCG012-2",
                badge: "Glass Kitchen",
                image: "img/products/smart-shaker-kitchen/1.jpg",
                images: [
                    "img/products/smart-shaker-kitchen/1.jpg",
                    "img/products/smart-shaker-kitchen/2.jpg",
                    "img/products/smart-shaker-kitchen/3.jpg",
                    "img/products/smart-shaker-kitchen/4.jpg",
                    "img/products/smart-shaker-kitchen/5.jpg",
                    "img/products/smart-shaker-kitchen/6.jpg"
                ],
                imageAlt: "White Shaker kitchen cabinets with walnut storage and dining island",
                imageAlts: [
                    "White Shaker kitchen cabinets with walnut display storage",
                    "Modern white and walnut kitchen island cabinet layout",
                    "Shaker kitchen with dining island and integrated wine storage",
                    "White kitchen wall cabinets above black countertop and sink",
                    "Walnut kitchen wine rack and hanging glass storage detail",
                    "White base cabinets with black countertop and double sink"
                ],
                price: 638,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A white and walnut kitchen composition combining clean Shaker-inspired fronts, glass elements and dedicated wine and dining storage.",
                seoDescription: "Smart Shaker kitchen cabinets with white fronts, walnut storage and glass elements. Model OLCG012-2, from USD 638 per metre.",
                highlights: ["White and walnut two-tone design", "Wine and glass storage features", "Flexible island and dining configuration"],
                specifications: {
                    "Model": "OLCG012-2",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Glass",
                    "Door finish": "Lacquer",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/glass-kitchen-cabinet/62749646.html"
            },
            {
                id: "modern-glass-kitchen",
                url: "products/modern-glass-front-kitchen",
                category: "cabinetry",
                name: "Modern Glass-Front Kitchen with Wine Storage",
                code: "OLCG025-2",
                badge: "Glass Kitchen",
                image: "img/products/modern-glass-kitchen/1.jpg",
                images: [
                    "img/products/modern-glass-kitchen/1.jpg",
                    "img/products/modern-glass-kitchen/2.jpg",
                    "img/products/modern-glass-kitchen/3.jpg",
                    "img/products/modern-glass-kitchen/4.jpg",
                    "img/products/modern-glass-kitchen/5.jpg",
                    "img/products/modern-glass-kitchen/6.jpg"
                ],
                imageAlt: "Modern glass-front kitchen cabinets with walnut wine storage and island",
                imageAlts: [
                    "Modern grey and walnut glass-front kitchen with island",
                    "Tall kitchen wine storage cabinet beside integrated appliances",
                    "Grey modular kitchen island with walnut dining extension",
                    "Modern kitchen cabinet system with pendant-lit island",
                    "Glass-front wall cabinets and walnut open kitchen storage",
                    "Modular kitchen cabinet components on a white background"
                ],
                price: 638,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A modern grey and walnut kitchen system with glass-front display cabinets, integrated appliances and a space-efficient wine-storage tower.",
                seoDescription: "Modern glass-front kitchen cabinets with grey and walnut finishes, island and wine storage. Model OLCG025-2, from USD 638 per metre.",
                highlights: ["Glass-front display cabinetry", "Integrated wine-storage tower", "Coordinated island and appliance units"],
                specifications: {
                    "Model": "OLCG025-2",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Solid wood",
                    "Door finish": "Glass",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/glass-kitchen-cabinet/62749774.html"
            },
            {
                id: "blue-melamine-kitchen",
                url: "products/blue-melamine-modular-kitchen",
                category: "cabinetry",
                name: "Blue Melamine Modular Kitchen",
                code: "OLCG018-2",
                badge: "Melamine Kitchen",
                image: "img/products/blue-melamine-kitchen/1.jpg",
                images: [
                    "img/products/blue-melamine-kitchen/1.jpg",
                    "img/products/blue-melamine-kitchen/2.jpg",
                    "img/products/blue-melamine-kitchen/3.jpg",
                    "img/products/blue-melamine-kitchen/4.jpg",
                    "img/products/blue-melamine-kitchen/5.jpg",
                    "img/products/blue-melamine-kitchen/6.jpg"
                ],
                imageAlt: "Blue and light wood melamine modular kitchen cabinets",
                imageAlts: [
                    "Blue and light wood melamine L-shaped kitchen cabinets",
                    "Light wood modular kitchen cabinets with open shelves",
                    "Black-framed glass wall cabinet detail in a blue kitchen",
                    "Blue melamine base cabinets with light wood wall cabinets",
                    "Blue handleless kitchen cabinets with white countertop",
                    "Quartz island countertop and blue melamine kitchen cabinets"
                ],
                price: 351,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A practical blue and light-wood melamine kitchen for apartments, with handleless base units, open shelving and configurable storage.",
                seoDescription: "Blue melamine modular kitchen cabinets for apartments with light wood storage and quartz countertop. Model OLCG018-2, from USD 351 per metre.",
                highlights: ["Blue and light-wood colour palette", "Handleless modern cabinet fronts", "Apartment-friendly modular planning"],
                specifications: {
                    "Model": "OLCG018-2",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749347.html"
            },
            {
                id: "modern-melamine-storage-kitchen",
                url: "products/modern-melamine-storage-kitchen",
                category: "cabinetry",
                name: "Modern Melamine Kitchen with Integrated Storage",
                code: "OLCG004",
                badge: "Melamine Kitchen",
                image: "img/products/modern-melamine-storage-kitchen/1.jpg",
                images: [
                    "img/products/modern-melamine-storage-kitchen/1.jpg",
                    "img/products/modern-melamine-storage-kitchen/2.jpg",
                    "img/products/modern-melamine-storage-kitchen/3.jpg",
                    "img/products/modern-melamine-storage-kitchen/4.jpg",
                    "img/products/modern-melamine-storage-kitchen/5.jpg",
                    "img/products/modern-melamine-storage-kitchen/6.jpg"
                ],
                imageAlt: "Modern neutral melamine kitchen cabinets with integrated storage accessories",
                imageAlts: [
                    "Neutral melamine kitchen cabinets with open shelf storage",
                    "Kitchen sink storage system with dish and glass organisers",
                    "Lift-up kitchen wall cabinet with organised shelving",
                    "Pull-out kitchen pantry accessory inside melamine cabinetry",
                    "Integrated oven and appliance tower in a modern kitchen",
                    "Pull-out cookware organiser fitted inside a kitchen drawer"
                ],
                price: 509,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A neutral melamine kitchen system built around accessible storage, including lift-up wall units, pull-out pantry fittings and appliance towers.",
                seoDescription: "Modern melamine kitchen cabinets with lift-up storage, pull-out pantry fittings and appliance tower. Model OLCG004, from USD 509 per metre.",
                highlights: ["Integrated pull-out storage accessories", "Lift-up wall cabinet options", "Coordinated appliance tower"],
                specifications: {
                    "Model": "OLCG004",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749390.html"
            },
            {
                id: "blue-minimalist-kitchen",
                url: "products/blue-minimalist-kitchen",
                category: "cabinetry",
                name: "Blue Minimalist Modular Kitchen",
                code: "OLCG018-1",
                badge: "Melamine Kitchen",
                image: "img/products/blue-minimalist-kitchen/1.jpg",
                images: [
                    "img/products/blue-minimalist-kitchen/1.jpg",
                    "img/products/blue-minimalist-kitchen/2.jpg",
                    "img/products/blue-minimalist-kitchen/3.jpg",
                    "img/products/blue-minimalist-kitchen/4.jpg",
                    "img/products/blue-minimalist-kitchen/5.jpg",
                    "img/products/blue-minimalist-kitchen/6.jpg"
                ],
                imageAlt: "Blue and pale wood minimalist modular kitchen cabinets",
                imageAlts: [
                    "Blue and pale wood minimalist L-shaped kitchen cabinets",
                    "Handleless grey-blue base cabinets with light wood wall units",
                    "Black-framed glass kitchen cabinet and pendant light detail",
                    "Blue modular kitchen cabinets with quartz worktop",
                    "Handleless blue kitchen drawers and appliance wall",
                    "Quartz kitchen island beside blue melamine cabinets"
                ],
                price: 351,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A cool blue and pale-wood modular kitchen with handleless fronts, glass display storage and a flexible apartment-ready layout.",
                seoDescription: "Blue minimalist melamine modular kitchen cabinets with handleless fronts and quartz worktop. Model OLCG018-1, from USD 351 per metre.",
                highlights: ["Blue and pale-wood finish palette", "Handleless flat-front cabinetry", "Glass display and open storage options"],
                specifications: {
                    "Model": "OLCG018-1",
                    "Application": "Apartment",
                    "Design style": "Modern minimalist",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Standard hinges": "Blum",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Country of origin": "China"
                },
                customisationOptions: [
                    "Cabinet dimensions and layout",
                    "Door colours and finishes",
                    "Countertop colours and thicknesses",
                    "Handles and hardware",
                    "Internal storage accessories",
                    "Sink and appliance integration",
                    "Alternative materials according to model and project requirements",
                    "Other requirements — contact us"
                ],
                customisationNote: "Final specifications are confirmed through drawings, material samples and the approved quotation before production.",
                commercialInformation: {
                    "Indicative price": "From USD 351 per metre",
                    "Minimum order": "1 metre",
                    "Currency": "USD",
                    "Payment method": "T/T only",
                    "Payment terms": "30% deposit upon order confirmation and 70% balance before shipment",
                    "Production lead time": "Approximately 30–40 days after confirmation of drawings, materials and deposit",
                    "Packaging": "Flat-pack or assembled export packaging according to project requirements",
                    "Trade terms": "EXW, FOB and CIF",
                    "DDP delivery": "Available for selected destinations, subject to the final delivery address and local import requirements",
                    "Port of loading": "Ningbo, China",
                    "Warranty": "One year",
                    "Factory inspection": "Buyers or their appointed representatives may inspect the goods at the factory by appointment",
                    "Video inspection": "Remote video inspection is available before shipment"
                },
                commercialNote: "Prices shown on the website are indicative starting prices. Final pricing depends on dimensions, materials, hardware, accessories, order quantity and delivery destination.",
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749354.html"
            },
            {
                id: "home-improvement-modular-kitchen",
                url: "products/home-improvement-modular-kitchen",
                category: "cabinetry",
                name: "Neutral Modular Kitchen for Home Renovation",
                code: "OLCG035",
                badge: "Melamine Kitchen",
                image: "img/products/home-improvement-modular-kitchen/1.jpg",
                images: [
                    "img/products/home-improvement-modular-kitchen/1.jpg",
                    "img/products/home-improvement-modular-kitchen/2.jpg",
                    "img/products/home-improvement-modular-kitchen/3.jpg",
                    "img/products/home-improvement-modular-kitchen/4.jpg",
                    "img/products/home-improvement-modular-kitchen/5.jpg",
                    "img/products/home-improvement-modular-kitchen/6.jpg"
                ],
                imageAlt: "Neutral melamine modular kitchen for home renovation",
                imageAlts: [
                    "Neutral L-shaped melamine kitchen cabinets for renovation",
                    "Beige and grey handleless modular kitchen with window",
                    "Compact L-shaped kitchen cabinets with integrated hob",
                    "Tall neutral kitchen cabinets with open display niche",
                    "Handleless base cabinets and black quartz countertop",
                    "Dark quartz worktop and neutral melamine drawer fronts"
                ],
                price: 351,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A compact neutral-toned cabinet system for apartment renovation, combining handleless storage, display niches and an efficient L-shaped plan.",
                seoDescription: "Neutral melamine modular kitchen cabinets for apartment and home renovation. Model OLCG035, from USD 351 per metre.",
                highlights: ["Calm neutral finish combination", "Efficient L-shaped planning", "Integrated open display storage"],
                specifications: {
                    "Model": "OLCG035",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749440.html"
            },
            {
                id: "custom-apartment-kitchen",
                url: "products/custom-apartment-kitchen",
                category: "cabinetry",
                name: "Custom Grey Apartment Kitchen",
                code: "OL62749344",
                badge: "Melamine Kitchen",
                image: "img/products/custom-apartment-kitchen/1.jpg",
                images: [
                    "img/products/custom-apartment-kitchen/1.jpg",
                    "img/products/custom-apartment-kitchen/2.jpg",
                    "img/products/custom-apartment-kitchen/3.jpg",
                    "img/products/custom-apartment-kitchen/4.jpg",
                    "img/products/custom-apartment-kitchen/5.jpg",
                    "img/products/custom-apartment-kitchen/6.jpg"
                ],
                imageAlt: "Custom grey and warm wood apartment kitchen cabinets",
                imageAlts: [
                    "Custom grey apartment kitchen with warm wood open shelving",
                    "Grey and wood modular kitchen with integrated oven tower",
                    "Compact apartment kitchen cabinets with marble-look worktop",
                    "Grey handleless kitchen drawers and integrated gas hob",
                    "Warm wood appliance niche within grey kitchen cabinetry",
                    "Tall grey storage cabinets with open wood display niches"
                ],
                price: 351,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A tailored grey and warm-wood kitchen for apartments, with an appliance tower, open niches and a clean handleless storage layout.",
                seoDescription: "Custom grey melamine apartment kitchen cabinets with warm wood niches and appliance tower. Model OL62749344, from USD 351 per metre.",
                highlights: ["Grey and warm-wood combination", "Integrated tall appliance unit", "Customisable open display niches"],
                specifications: {
                    "Model": "OL62749344",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Custom modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749344.html"
            },
            {
                id: "minimalist-mini-kitchen",
                url: "products/minimalist-mini-kitchen",
                category: "cabinetry",
                name: "Minimalist White and Wood Mini Kitchen",
                code: "OLCG022",
                badge: "Melamine Kitchen",
                image: "img/products/minimalist-mini-kitchen/1.jpg",
                images: [
                    "img/products/minimalist-mini-kitchen/1.jpg",
                    "img/products/minimalist-mini-kitchen/2.jpg",
                    "img/products/minimalist-mini-kitchen/3.jpg",
                    "img/products/minimalist-mini-kitchen/4.jpg",
                    "img/products/minimalist-mini-kitchen/5.jpg",
                    "img/products/minimalist-mini-kitchen/6.jpg"
                ],
                imageAlt: "Minimalist white and wood mini kitchen cabinets",
                imageAlts: [
                    "White and wood mini kitchen cabinets for a small apartment",
                    "Minimalist compact kitchen with white wall cabinets",
                    "Wood-effect base cabinets and white handleless wall units",
                    "Small modular kitchen with peninsula dining counter",
                    "White kitchen wall cabinets with wood open display niches",
                    "Compact kitchen sink cabinet below apartment window"
                ],
                price: 351,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A bright small-space kitchen pairing white upper cabinets with warm wood-effect bases, practical niches and an optional dining peninsula.",
                seoDescription: "Minimalist white and wood mini kitchen cabinets for small apartments. Model OLCG022, from USD 351 per metre.",
                highlights: ["Small-apartment cabinet layout", "White and wood-effect finishes", "Optional peninsula dining counter"],
                specifications: {
                    "Model": "OLCG022",
                    "Application": "Apartment",
                    "Design style": "Modern minimalist",
                    "Cabinet type": "Mini modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749408.html"
            },
            {
                id: "wooden-mini-kitchen",
                url: "products/grey-blush-modular-kitchen",
                category: "cabinetry",
                name: "Grey and Blush Modular Kitchen",
                code: "OLCG021",
                badge: "Melamine Kitchen",
                image: "img/products/wooden-mini-kitchen/1.jpg",
                images: [
                    "img/products/wooden-mini-kitchen/1.jpg",
                    "img/products/wooden-mini-kitchen/2.jpg",
                    "img/products/wooden-mini-kitchen/3.jpg",
                    "img/products/wooden-mini-kitchen/4.jpg",
                    "img/products/wooden-mini-kitchen/5.jpg",
                    "img/products/wooden-mini-kitchen/6.jpg"
                ],
                imageAlt: "Grey and blush wood-effect modular kitchen cabinets",
                imageAlts: [
                    "Grey and blush modular kitchen cabinets with dining island",
                    "Two-tone grey and blush kitchen with quartz peninsula",
                    "Open-plan kitchen with grey cabinets and blush accents",
                    "Grey handleless kitchen cabinets with pink open shelving",
                    "Grey and muted blush kitchen wall cabinet arrangement",
                    "Grey base and wall cabinets with marble-look backsplash"
                ],
                price: 351,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A distinctive grey and muted-blush cabinet scheme for open-plan homes, combining handleless storage with island and display options.",
                seoDescription: "Grey and blush melamine modular kitchen cabinets with island and open storage. Model OLCG021, from USD 351 per metre.",
                highlights: ["Grey and muted-blush colour scheme", "Open-plan island configuration", "Handleless storage and display units"],
                specifications: {
                    "Model": "OLCG021",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749407.html"
            },
            {
                id: "grey-compact-apartment-kitchen",
                url: "products/grey-compact-apartment-kitchen",
                category: "cabinetry",
                name: "Compact Grey Apartment Kitchen",
                code: "OLCG008",
                badge: "Melamine Kitchen",
                image: "img/products/grey-compact-apartment-kitchen/1.jpg",
                images: [
                    "img/products/grey-compact-apartment-kitchen/1.jpg",
                    "img/products/grey-compact-apartment-kitchen/2.jpg",
                    "img/products/grey-compact-apartment-kitchen/3.jpg",
                    "img/products/grey-compact-apartment-kitchen/4.jpg",
                    "img/products/grey-compact-apartment-kitchen/5.jpg",
                    "img/products/grey-compact-apartment-kitchen/6.jpg"
                ],
                imageAlt: "Compact grey melamine apartment kitchen cabinets",
                imageAlts: [
                    "Compact grey and white apartment kitchen cabinet layout",
                    "Grey small kitchen with tall appliance storage cabinet",
                    "Compact modular kitchen with integrated oven tower",
                    "Grey handleless base cabinets with patterned backsplash",
                    "White wall cabinets and grey base units for a small kitchen",
                    "Compact white upper cabinets with open display cubbies"
                ],
                price: 351,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A compact grey-and-white kitchen for apartments, combining handleless storage, an appliance tower and an efficient single-wall layout.",
                seoDescription: "Compact grey melamine apartment kitchen cabinets with appliance tower and quartz worktop. Model OLCG008, from USD 351 per metre.",
                highlights: ["Space-efficient single-wall layout", "Integrated tall appliance storage", "Custom grey and white finishes"],
                specifications: {
                    "Model": "OLCG008",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749393.html"
            },
            {
                id: "modern-island-storage-kitchen",
                url: "products/modern-island-storage-kitchen",
                category: "cabinetry",
                name: "Grey Melamine Island Kitchen",
                code: "OLCG014",
                badge: "Melamine Kitchen",
                image: "img/products/modern-island-storage-kitchen/1.jpg",
                images: [
                    "img/products/modern-island-storage-kitchen/1.jpg",
                    "img/products/modern-island-storage-kitchen/2.jpg",
                    "img/products/modern-island-storage-kitchen/3.jpg",
                    "img/products/modern-island-storage-kitchen/4.jpg",
                    "img/products/modern-island-storage-kitchen/5.jpg",
                    "img/products/modern-island-storage-kitchen/6.jpg"
                ],
                imageAlt: "Grey melamine kitchen cabinets with island storage",
                imageAlts: [
                    "Grey melamine kitchen with large island and integrated lighting",
                    "Open-plan grey kitchen cabinets with dining island",
                    "Grey handleless wall and base cabinets with quartz worktop",
                    "Kitchen island sink facing grey modular cabinetry",
                    "Quartz kitchen island with seating and grey storage units",
                    "Apartment kitchen sink area beside a full-height window"
                ],
                price: 320,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A refined grey melamine kitchen with a generous island, handleless storage and coordinated tall units for open-plan apartment interiors.",
                seoDescription: "Grey melamine island kitchen cabinets for open-plan apartments with quartz worktop and handleless storage. Model OLCG014, from USD 320 per metre.",
                highlights: ["Large storage and dining island", "Grey melamine cabinet fronts", "Open-plan apartment configuration"],
                specifications: {
                    "Model": "OLCG014",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Melamine board",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749363.html"
            },
            {
                id: "lacquer-apartment-kitchen",
                url: "products/grey-lacquer-island-kitchen",
                category: "cabinetry",
                name: "Grey Lacquer Island Kitchen",
                code: "OL62749324",
                badge: "Lacquer Kitchen",
                image: "img/products/lacquer-apartment-kitchen/1.jpg",
                images: [
                    "img/products/lacquer-apartment-kitchen/1.jpg",
                    "img/products/lacquer-apartment-kitchen/2.jpg",
                    "img/products/lacquer-apartment-kitchen/3.jpg",
                    "img/products/lacquer-apartment-kitchen/4.jpg",
                    "img/products/lacquer-apartment-kitchen/5.jpg",
                    "img/products/lacquer-apartment-kitchen/6.jpg"
                ],
                imageAlt: "High-end grey lacquer kitchen cabinets with island",
                imageAlts: [
                    "High-end grey lacquer kitchen with broad island",
                    "Grey lacquer apartment kitchen in an open-plan room",
                    "Quartz island and lacquer storage beside full-height windows",
                    "Grey lacquer kitchen island with integrated sink and seating",
                    "Handleless lacquer cabinets with illuminated backsplash",
                    "Grey lacquer wall cabinets and quartz island sink"
                ],
                price: 320,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A polished grey lacquer configuration for contemporary apartments, featuring an expansive quartz island and streamlined handleless cabinetry.",
                seoDescription: "Grey lacquer island kitchen cabinets for modern apartments with handleless storage and quartz surfaces. Model OL62749324, from USD 320 per metre.",
                highlights: ["Smooth lacquer door finish", "Expansive quartz island", "Streamlined handleless cabinetry"],
                specifications: {
                    "Model": "OL62749324",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "MDF",
                    "Door finish": "Lacquer",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749324.html"
            },
            {
                id: "blue-wood-storage-kitchen",
                url: "products/blue-wood-storage-kitchen",
                category: "cabinetry",
                name: "Blue and Black Storage Kitchen",
                code: "OLCG018",
                badge: "Melamine Kitchen",
                image: "img/products/blue-wood-storage-kitchen/1.jpg",
                images: [
                    "img/products/blue-wood-storage-kitchen/1.jpg",
                    "img/products/blue-wood-storage-kitchen/2.jpg",
                    "img/products/blue-wood-storage-kitchen/3.jpg",
                    "img/products/blue-wood-storage-kitchen/4.jpg",
                    "img/products/blue-wood-storage-kitchen/5.jpg",
                    "img/products/blue-wood-storage-kitchen/6.jpg"
                ],
                imageAlt: "Blue and black minimalist kitchen storage cabinets",
                imageAlts: [
                    "Blue and black kitchen cabinets with central island",
                    "Blue modular kitchen with black glass tall storage",
                    "Open-plan blue kitchen with dining island and display cabinets",
                    "Blue appliance tower with open pantry shelving",
                    "Blue wall cabinets and white quartz worktop with sink",
                    "Black glass storage cabinets beside a kitchen dining area"
                ],
                price: 351,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A confident blue-and-black storage system with glass-front tall units, open shelving and an island designed for cooking and casual dining.",
                seoDescription: "Blue and black melamine kitchen cabinets with island, glass-front storage and quartz worktop. Model OLCG018, from USD 351 per metre.",
                highlights: ["Blue and black colour combination", "Glass-front tall storage", "Multi-purpose cooking and dining island"],
                specifications: {
                    "Model": "OLCG018",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "Vinyl wrap / thermofoil",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749401.html"
            },
            {
                id: "complete-value-kitchen",
                url: "products/warm-wood-complete-kitchen",
                category: "cabinetry",
                name: "Warm Wood Complete Kitchen with Island",
                code: "OLCG055",
                badge: "Melamine Kitchen",
                image: "img/products/complete-value-kitchen/1.jpg",
                images: [
                    "img/products/complete-value-kitchen/1.jpg",
                    "img/products/complete-value-kitchen/2.jpg",
                    "img/products/complete-value-kitchen/3.jpg",
                    "img/products/complete-value-kitchen/4.jpg",
                    "img/products/complete-value-kitchen/5.jpg",
                    "img/products/complete-value-kitchen/6.jpg"
                ],
                imageAlt: "Warm wood complete modular kitchen with island",
                imageAlts: [
                    "Warm wood and beige complete kitchen with island seating",
                    "Wood-effect modular kitchen with quartz island and tall units",
                    "Complete apartment kitchen with integrated oven and dining island",
                    "Warm wood kitchen storage wall with beige island cabinetry",
                    "Wood-effect wall cabinets with illuminated marble-look backsplash",
                    "Quartz kitchen island with integrated sink and timber dining extension"
                ],
                price: 640,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A coordinated warm-wood kitchen package with tall appliance storage, a quartz island and an integrated dining extension for complete layouts.",
                seoDescription: "Warm wood complete modular kitchen with island, appliance storage and quartz worktop. Model OLCG055, from USD 640 per metre.",
                highlights: ["Coordinated complete kitchen layout", "Tall appliance and pantry storage", "Island with integrated dining extension"],
                specifications: {
                    "Model": "OLCG055",
                    "Application": "Apartment",
                    "Design style": "Modern",
                    "Cabinet type": "Modular kitchen cabinets",
                    "Carcase material": "Particleboard",
                    "Door material": "Particleboard",
                    "Door finish": "PVC membrane",
                    "Countertop": "Artificial quartz",
                    "Countertop edge": "Flat edge / eased edge",
                    "Environmental standard": "E1 / E0",
                    "Minimum order": "1 metre",
                    "Production lead time": "Approximately 30–40 days"
                },
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749754.html"
            },
            {
                id: "minimalist-full-kitchen",
                url: "products/white-wood-minimalist-kitchen",
                category: "cabinetry",
                name: "White and Wood Minimalist Kitchen",
                code: "OL62749783",
                badge: "Melamine Kitchen",
                image: "img/products/minimalist-full-kitchen/1.jpg",
                images: ["img/products/minimalist-full-kitchen/1.jpg","img/products/minimalist-full-kitchen/2.jpg","img/products/minimalist-full-kitchen/3.jpg","img/products/minimalist-full-kitchen/4.jpg","img/products/minimalist-full-kitchen/5.jpg","img/products/minimalist-full-kitchen/6.jpg"],
                imageAlt: "White and wood minimalist apartment kitchen cabinets",
                imageAlts: ["White and wood minimalist kitchen with peninsula","Wood-effect base cabinets and white handleless wall units","L-shaped white and wood kitchen beside a full-height window","Compact peninsula kitchen with integrated sink and oven","Open-plan minimalist kitchen with breakfast seating","White wall units and wood-effect base cabinets"],
                price: 350,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A bright white-and-wood kitchen designed for compact homes, combining open display niches, handleless storage and a practical peninsula.",
                seoDescription: "White and wood minimalist kitchen cabinets with peninsula and quartz worktop for apartments. Model OL62749783, from USD 350 per metre.",
                highlights: ["White and natural wood palette","Space-saving peninsula layout","Open display and closed storage"],
                specifications: {"Model":"OL62749783","Application":"Apartment","Design style":"Modern minimalist","Cabinet type":"Modular kitchen cabinets","Carcase material":"E1 particleboard / plywood / MDF","Door material":"Melamine board","Door finish":"Melamine","Countertop":"Artificial quartz","Countertop edge":"Flat edge / eased edge","Environmental standard":"E1 / E0","Minimum order":"1 metre","Production lead time":"Approximately 30–40 days"},
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749783.html"
            },
            {
                id: "dark-grey-solid-wood-kitchen",
                url: "products/dark-grey-corner-kitchen",
                category: "cabinetry",
                name: "Dark Grey Corner Kitchen",
                code: "OLCG035-1",
                badge: "Melamine Kitchen",
                image: "img/products/dark-grey-solid-wood-kitchen/1.jpg",
                images: ["img/products/dark-grey-solid-wood-kitchen/1.jpg","img/products/dark-grey-solid-wood-kitchen/2.jpg","img/products/dark-grey-solid-wood-kitchen/3.jpg","img/products/dark-grey-solid-wood-kitchen/4.jpg","img/products/dark-grey-solid-wood-kitchen/5.jpg","img/products/dark-grey-solid-wood-kitchen/6.jpg"],
                imageAlt: "Dark grey handleless corner kitchen cabinets",
                imageAlts: ["Dark grey and wood-effect L-shaped kitchen cabinets","Handleless corner kitchen with black quartz worktop","Dark grey kitchen base units and pale wood wall cabinets","Integrated corner drawers with slim black handles","Tall grey storage cabinet with open timber niche","Black quartz countertop and grey drawer detail"],
                price: 351,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A compact dark-grey corner kitchen with warm wood accents, slim integrated handles and a durable black worktop for efficient apartment layouts.",
                seoDescription: "Dark grey corner kitchen cabinets with wood accents and black quartz worktop. Model OLCG035-1, from USD 351 per metre.",
                highlights: ["Efficient L-shaped layout","Dark grey and wood finish combination","Slim integrated handle profile"],
                specifications: {"Model":"OLCG035-1","Application":"Apartment","Design style":"Modern","Cabinet type":"Modular kitchen cabinets","Carcase material":"Particleboard","Door material":"Particleboard","Door finish":"Vinyl wrap / thermofoil","Countertop":"Artificial quartz","Countertop edge":"Flat edge / eased edge","Environmental standard":"E1 / E0","Minimum order":"1 metre","Production lead time":"Approximately 30–40 days"},
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749558.html"
            },
            {
                id: "white-modular-kitchen",
                url: "products/monochrome-modular-island-kitchen",
                category: "cabinetry",
                name: "Monochrome Modular Island Kitchen",
                code: "OLCG040",
                badge: "Melamine Kitchen",
                image: "img/products/white-modular-kitchen/1.jpg",
                images: ["img/products/white-modular-kitchen/1.jpg","img/products/white-modular-kitchen/2.jpg","img/products/white-modular-kitchen/3.jpg","img/products/white-modular-kitchen/4.jpg","img/products/white-modular-kitchen/5.jpg","img/products/white-modular-kitchen/6.jpg"],
                imageAlt: "Monochrome grey and white modular island kitchen",
                imageAlts: ["Grey and white modular kitchen with island seating","Monochrome kitchen island and full-height storage","Open-plan grey kitchen with dining worktop extension","White wall cabinets with black display niche","Black glass tall cabinet with vertical lighting","Dark backsplash and quartz kitchen worktop detail"],
                price: 363,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A monochrome kitchen system combining white upper cabinets, textured grey storage, black display details and a flexible island for dining and preparation.",
                seoDescription: "Monochrome grey and white modular kitchen with island, display storage and quartz worktop. Model OLCG040, from USD 363 per metre.",
                highlights: ["Layered monochrome material palette","Island for dining and preparation","Integrated display and tall storage"],
                specifications: {"Model":"OLCG040","Application":"Apartment","Design style":"Modern","Cabinet type":"Modular kitchen cabinets","Carcase material":"Particleboard","Door material":"Melamine board","Door finish":"Vinyl wrap / thermofoil","Countertop":"Artificial quartz","Countertop edge":"Flat edge / eased edge","Environmental standard":"E1 / E0","Minimum order":"1 metre","Production lead time":"Approximately 30–40 days"},
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749443.html"
            },
            {
                id: "pink-modular-kitchen",
                url: "products/soft-pink-modular-kitchen",
                category: "cabinetry",
                name: "Soft Pink Modular Kitchen with Island",
                code: "OLCG013-3",
                badge: "Melamine Kitchen",
                image: "img/products/pink-modular-kitchen/1.jpg",
                images: ["img/products/pink-modular-kitchen/1.jpg","img/products/pink-modular-kitchen/2.jpg","img/products/pink-modular-kitchen/3.jpg","img/products/pink-modular-kitchen/4.jpg","img/products/pink-modular-kitchen/5.jpg","img/products/pink-modular-kitchen/6.jpg"],
                imageAlt: "Soft pink and grey modular kitchen with island",
                imageAlts: ["Soft pink and grey kitchen with central island","Pink modular kitchen island with integrated sink","Warm grey tall cabinets and soft pink island fronts","Quartz island worktop with integrated hob detail","Open-plan soft pink kitchen with breakfast seating","Pink and grey wall cabinets with open display niche"],
                price: 509,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A soft pink and warm-grey kitchen for contemporary homes, with a central island, integrated appliances and a calm tonal finish combination.",
                seoDescription: "Soft pink and grey modular kitchen cabinets with island and quartz worktop. Model OLCG013-3, from USD 509 per metre.",
                highlights: ["Soft pink and warm-grey finishes","Central island with integrated functions","Coordinated tall appliance storage"],
                specifications: {"Model":"OLCG013-3","Application":"Apartment","Design style":"Modern","Cabinet type":"Modular kitchen cabinets","Carcase material":"Particleboard","Door material":"Melamine board","Door finish":"Vinyl wrap / thermofoil","Countertop":"Artificial quartz","Countertop edge":"Flat edge / eased edge","Environmental standard":"E1 / E0","Minimum order":"1 metre","Production lead time":"Approximately 30–40 days"},
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749694.html"
            },
            {
                id: "custom-lacquer-kitchen",
                url: "products/walnut-lacquer-storage-kitchen",
                category: "cabinetry",
                name: "Walnut Lacquer Kitchen with Pull-Out Storage",
                code: "OLCG045",
                badge: "Lacquer Kitchen",
                image: "img/products/custom-lacquer-kitchen/1.jpg",
                images: ["img/products/custom-lacquer-kitchen/1.jpg","img/products/custom-lacquer-kitchen/2.jpg","img/products/custom-lacquer-kitchen/3.jpg","img/products/custom-lacquer-kitchen/4.jpg","img/products/custom-lacquer-kitchen/5.jpg","img/products/custom-lacquer-kitchen/6.jpg"],
                imageAlt: "Walnut lacquer kitchen cabinets with pull-out storage",
                imageAlts: ["Walnut and black lacquer kitchen cabinet wall","Warm walnut kitchen cabinets with metallic backsplash","Walnut and grey kitchen with angular quartz island","Pull-out wire basket inside a base cabinet","Walnut veneer door edge and cabinet construction detail","Pull-out dish basket storage system"],
                price: 492,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A warm walnut and dark lacquer kitchen featuring a sculptural island, metallic backsplash and integrated pull-out storage accessories.",
                seoDescription: "Walnut lacquer kitchen cabinets with quartz island and pull-out storage accessories. Model OLCG045, from USD 492 per metre.",
                highlights: ["Walnut and dark lacquer combination","Integrated pull-out basket storage","Sculptural island and metallic backsplash"],
                specifications: {"Model":"OLCG045","Application":"Apartment","Design style":"Modern","Cabinet type":"Modular kitchen cabinets","Carcase material":"Particleboard","Door material":"Melamine board","Door finish":"Lacquer","Countertop":"Artificial quartz","Countertop edge":"Flat edge / eased edge","Environmental standard":"E1 / E0","Minimum order":"1 metre","Production lead time":"Approximately 30–40 days"},
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749718.html"
            },
            {
                id: "white-wood-peninsula-kitchen",
                url: "products/white-wood-peninsula-kitchen",
                category: "cabinetry",
                name: "White and Wood Peninsula Kitchen",
                code: "OLCG022-1",
                badge: "Melamine Kitchen",
                image: "img/products/white-wood-peninsula-kitchen/1.jpg",
                images: ["img/products/white-wood-peninsula-kitchen/1.jpg","img/products/white-wood-peninsula-kitchen/2.jpg","img/products/white-wood-peninsula-kitchen/3.jpg","img/products/white-wood-peninsula-kitchen/4.jpg","img/products/white-wood-peninsula-kitchen/5.jpg","img/products/white-wood-peninsula-kitchen/6.jpg"],
                imageAlt: "White and wood peninsula kitchen cabinets",
                imageAlts: ["White and wood kitchen with peninsula and sea-view windows","Handleless wood-effect base cabinets and white wall units","Compact peninsula kitchen with integrated black appliances","Open display niches beneath white kitchen wall cabinets","Artificial quartz worktop with integrated hob","Built-in black oven within a wood-effect tall cabinet"],
                price: 351,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A bright white-and-wood kitchen with a space-efficient peninsula, open display niches and handleless storage for contemporary apartments.",
                seoDescription: "White and wood peninsula kitchen cabinets with quartz worktop and handleless storage. Model OLCG022-1, from USD 351 per metre.",
                highlights: ["Space-efficient peninsula layout","White and natural wood finish combination","Integrated appliances and display niches"],
                specifications: {"Model":"OLCG022-1","Application":"Apartment","Design style":"Modern","Cabinet type":"Modular kitchen cabinets","Carcase material":"Particleboard","Door material":"Particleboard","Door finish":"Vinyl wrap / thermofoil","Countertop":"Artificial quartz","Countertop edge":"Flat edge / eased edge","Environmental standard":"E1 / E0","Minimum order":"1 metre","Production lead time":"Approximately 30–40 days"},
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749499.html"
            },
            {
                id: "grey-wood-linear-kitchen",
                url: "products/grey-wood-linear-kitchen",
                category: "cabinetry",
                name: "Grey Wood Linear Kitchen",
                code: "OLCG006-3",
                badge: "Melamine Kitchen",
                image: "img/products/grey-wood-linear-kitchen/1.jpg",
                images: ["img/products/grey-wood-linear-kitchen/1.jpg","img/products/grey-wood-linear-kitchen/2.jpg","img/products/grey-wood-linear-kitchen/3.jpg","img/products/grey-wood-linear-kitchen/4.jpg","img/products/grey-wood-linear-kitchen/5.jpg","img/products/grey-wood-linear-kitchen/6.jpg"],
                imageAlt: "Grey wood linear kitchen cabinets with dining table",
                imageAlts: ["Compact grey wood linear kitchen with integrated oven","Grey wood kitchen cabinets with attached dining table","Handleless base drawers beneath a quartz worktop","Compact cooking zone with black hood and hob","Grey glass-front storage cabinet beside the kitchen","Open-plan linear kitchen and dining area"],
                price: 351,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A compact linear kitchen combining soft grey wall units, textured wood-effect fronts and an attached dining surface for efficient open-plan living.",
                seoDescription: "Grey wood linear kitchen cabinets with dining table, quartz worktop and integrated appliances. Model OLCG006-3, from USD 351 per metre.",
                highlights: ["Compact single-wall configuration","Integrated dining and preparation surface","Grey and textured wood-effect finishes"],
                specifications: {"Model":"OLCG006-3","Application":"Apartment","Design style":"Modern","Cabinet type":"Modular kitchen cabinets","Carcase material":"Particleboard","Door material":"Melamine board","Door finish":"Vinyl wrap / thermofoil","Countertop":"Artificial quartz","Countertop edge":"Flat edge / eased edge","Environmental standard":"E1 / E0","Minimum order":"1 metre","Production lead time":"Approximately 30–40 days"},
                sourceUrl: "https://www.oulin-oversea.com/melamine-kitchen-cabinet/62749691.html"
            },
            {
                id: "navy-handleless-kitchen",
                url: "products/navy-handleless-kitchen",
                category: "cabinetry",
                name: "Navy Handleless Kitchen",
                code: "OLCG096",
                badge: "Lacquer Kitchen",
                image: "img/products/navy-handleless-kitchen/1.jpg",
                images: ["img/products/navy-handleless-kitchen/1.jpg","img/products/navy-handleless-kitchen/2.jpg","img/products/navy-handleless-kitchen/3.jpg","img/products/navy-handleless-kitchen/4.jpg","img/products/navy-handleless-kitchen/5.jpg","img/products/navy-handleless-kitchen/6.jpg"],
                imageAlt: "Navy handleless kitchen cabinets with glass storage",
                imageAlts: ["Navy handleless kitchen wall with illuminated backsplash","Grey variation of the handleless kitchen cabinet system","Navy lacquer cabinets with copper-toned tall accent","Graphite handleless kitchen with full-height storage","Dining area beside smoked-glass kitchen cabinets","Open-plan navy kitchen with reflective glass storage"],
                price: 751,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A streamlined navy kitchen wall with handleless cabinetry, smoked-glass tall storage and a warm metallic accent for sophisticated contemporary interiors.",
                seoDescription: "Navy handleless kitchen cabinets with smoked-glass tall storage and quartz worktop. Model OLCG096, from USD 751 per metre.",
                highlights: ["Deep navy handleless cabinet fronts","Smoked-glass full-height storage","Integrated lighting and metallic accent"],
                specifications: {"Model":"OLCG096","Application":"Apartment","Design style":"Modern","Cabinet type":"Modular kitchen cabinets","Carcase material":"Particleboard","Door material":"Solid wood","Door finish":"Solid wood / custom finish","Countertop":"Artificial quartz","Countertop edge":"Flat edge / eased edge","Environmental standard":"E1 / E0","Minimum order":"1 metre","Production lead time":"Approximately 30–40 days"},
                sourceUrl: "https://www.oulin-oversea.com/lacquer-kitchen-cabinet/62749313.html"
            },
            {
                id: "blue-shaker-corner-kitchen",
                url: "products/blue-shaker-corner-kitchen",
                category: "cabinetry",
                name: "Blue Shaker Corner Kitchen",
                code: "OLCG036",
                badge: "Shaker Kitchen",
                image: "img/products/blue-shaker-corner-kitchen/1.jpg",
                images: ["img/products/blue-shaker-corner-kitchen/1.jpg","img/products/blue-shaker-corner-kitchen/2.jpg","img/products/blue-shaker-corner-kitchen/3.jpg","img/products/blue-shaker-corner-kitchen/4.jpg","img/products/blue-shaker-corner-kitchen/5.jpg","img/products/blue-shaker-corner-kitchen/6.jpg"],
                imageAlt: "Blue shaker corner kitchen cabinets",
                imageAlts: ["Blue and white shaker corner kitchen cabinets","L-shaped blue shaker kitchen with quartz worktop","Blue base cabinets with white glass-front wall units","Mesh-front pantry and plate storage cabinet","Soft blue shaker drawers with slim dark handles","White quartz worktop and cooking zone detail"],
                price: 492,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A soft-blue Shaker kitchen with an efficient corner layout, white glass-front wall units and coordinated display storage for classic-modern homes.",
                seoDescription: "Blue shaker corner kitchen cabinets with glass-front wall units and white quartz worktop. Model OLCG036, from USD 492 per metre.",
                highlights: ["Efficient L-shaped corner layout","Blue Shaker fronts and glass wall units","Coordinated display and pantry storage"],
                specifications: {"Model":"OLCG036","Application":"Apartment","Design style":"European","Cabinet type":"Modular kitchen cabinets","Carcase material":"Particleboard","Door material":"Particleboard","Door finish":"Vinyl wrap / thermofoil","Countertop":"Artificial quartz","Countertop edge":"Flat edge / eased edge","Environmental standard":"E1 / E0","Minimum order":"1 metre","Production lead time":"Approximately 30–40 days"},
                sourceUrl: "https://www.oulin-oversea.com/lacquer-kitchen-cabinet/62749441.html"
            },
            {
                id: "teal-shaker-island-kitchen",
                url: "products/teal-shaker-island-kitchen",
                category: "cabinetry",
                name: "Teal Shaker Kitchen with Island",
                code: "OLCG028",
                badge: "Solid Wood Kitchen",
                image: "img/products/teal-shaker-island-kitchen/1.jpg",
                images: ["img/products/teal-shaker-island-kitchen/1.jpg","img/products/teal-shaker-island-kitchen/2.jpg","img/products/teal-shaker-island-kitchen/3.jpg","img/products/teal-shaker-island-kitchen/4.jpg","img/products/teal-shaker-island-kitchen/5.jpg","img/products/teal-shaker-island-kitchen/6.jpg"],
                imageAlt: "Teal shaker kitchen cabinets with island",
                imageAlts: ["Teal and white Shaker kitchen with central island","Teal tall pantry cabinets with integrated ovens","White cabinet wall with warm wood open storage","Teal Shaker island with breakfast seating","Raised-panel teal wall cabinets with brass handles","Teal and wood kitchen island with quartz worktop"],
                price: 751,
                pricePrefix: "From",
                priceUnit: "per metre",
                summary: "A character-rich teal Shaker kitchen combining solid-wood door styling, white cabinetry, warm timber accents and a practical central island.",
                seoDescription: "Teal shaker kitchen cabinets with island, solid-wood doors and quartz worktop. Model OLCG028, from USD 751 per metre.",
                highlights: ["Teal solid-wood Shaker door style","Central island with seating","White cabinetry and warm timber accents"],
                specifications: {"Model":"OLCG028","Application":"Apartment","Design style":"Modern Shaker","Cabinet type":"Modular kitchen cabinets","Carcase material":"Particleboard","Door material":"Solid wood","Door finish":"Solid wood / custom finish","Countertop":"Artificial quartz","Countertop edge":"Flat edge / eased edge","Environmental standard":"E1 / E0","Minimum order":"1 metre","Production lead time":"Approximately 30–40 days"},
                sourceUrl: "https://www.oulin-oversea.com/lacquer-kitchen-cabinet/62749417.html"
            }
        ]
    };
}());
